### ISSUE TITLE
OpenOCD complains about the debug module version

### ISSUE THREAD

**Issue by kaidoho** [westerndigitalcorporation/swerv_eh1_fpga#1]
Hi guys,

could you tell me which version of OpenOCD you've used while testing? 

I receive the following error code:
 
Info : JTAG tap: riscv.cpu tap/device found: 0x00000001 (mfg: 0x000 (<invalid>), part: 0x0000, ver: 0x0)
Error: OpenOCD only supports Debug Module version 2, not 0 (dmstatus=0x0)

Any thoughts on that?

Regards

**Comment by arupde171** [comment]
Could you please use the latest version of riscv-openocd from the github.
https://github.com/riscv/riscv-openocd.git

Regards,
Arup

**Comment by arupde171** [comment]
Please use riscv-openocd from the github (https://github.com/riscv/riscv-openocd.git) and checkout the latest commit: af3a034

**Comment by kaidoho** [comment]
Hi Arup,

thx that worked out nicely.

**Comment by zhuzhizhan** [comment]
> Please use riscv-openocd from the github (https://github.com/riscv/riscv-openocd.git) and checkout the latest commit: af3a034

Hi arupde171,

I use FT2232Hl to connect the core and I ran into the same problem. The log is:
Open On-Chip Debugger 0.10.0+dev-00530-gaf3a034b5 (2020-09-10-16:17)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
adapter speed: 100 kHz
Info : clock speed 100 kHz
Info : JTAG tap: riscv.cpu tap/device found: 0x00000001 (mfg: 0x000 (<invalid>), part: 0x0000, ver: 0x0)
Error: Debug Module did not become active. dmcontrol=0x0
Info : Listening on port 3333 for gdb connections
Error: Target not examined yet

How can I do for this problem.

**Comment by zhuzhizhan** [comment]
> > Please use riscv-openocd from the github (https://github.com/riscv/riscv-openocd.git) and checkout the latest commit: af3a034
> 
> Hi arupde171,
> 
> I use FT2232Hl to connect the core and I ran into the same problem. The log is:
> Open On-Chip Debugger 0.10.0+dev-00530-gaf3a034b5 (2020-09-10-16:17)
> Licensed under GNU GPL v2
> For bug reports, read
> http://openocd.org/doc/doxygen/bugs.html
> adapter speed: 100 kHz
> Info : clock speed 100 kHz
> Info : JTAG tap: riscv.cpu tap/device found: 0x00000001 (mfg: 0x000 (), part: 0x0000, ver: 0x0)
> Error: Debug Module did not become active. dmcontrol=0x0
> Info : Listening on port 3333 for gdb connections
> Error: Target not examined yet
> 
> How can I do for this problem.

Similar problem

**Comment by zhuzhizhan** [comment]
> > > Please use riscv-openocd from the github (https://github.com/riscv/riscv-openocd.git) and checkout the latest commit: af3a034
> > 
> > 
> > Hi arupde171,
> > I use FT2232Hl to connect the core and I ran into the same problem. The log is:
> > Open On-Chip Debugger 0.10.0+dev-00530-gaf3a034b5 (2020-09-10-16:17)
> > Licensed under GNU GPL v2
> > For bug reports, read
> > http://openocd.org/doc/doxygen/bugs.html
> > adapter speed: 100 kHz
> > Info : clock speed 100 kHz
> > Info : JTAG tap: riscv.cpu tap/device found: 0x00000001 (mfg: 0x000 (), part: 0x0000, ver: 0x0)
> > Error: Debug Module did not become active. dmcontrol=0x0
> > Info : Listening on port 3333 for gdb connections
> > Error: Target not examined yet
> > How can I do for this problem.
> 
> Similar problem

I have changed swerv_eh1's branch to 1.4 and solve this problem.
