### ISSUE TITLE
JTAG

### ISSUE THREAD

**Issue by mongsim** [westerndigitalcorporation/swerv_eh1_fpga#3]
Hello, can you point which JTAG you using for this project? There are many old JTAG ports on that site.

Thank you,

**Comment by arupde171** [comment]
You can use Olimex ARM-USB-Tiny-H connector.

Regards,
Arup

**Comment by zhuzhizhan** [comment]
> You can use Olimex ARM-USB-Tiny-H connector.
> 
> Regards,
> Arup

Hi,

I use the ft2232HL as the connector. Can it be used to debug?
I use it and get some log:
Open On-Chip Debugger 0.10.0+dev-00849-gcbb15587d (2020-09-10-11:59)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : clock speed 100 kHz
Info : JTAG tap: riscv.cpu tap/device found: 0x00000001 (mfg: 0x000 (<invalid>), part: 0x0000, ver: 0x0)
Error: Debug Module did not become active. dmcontrol=0x0
Info : Listening on port 3333 for gdb connections
Error: Target not examined yet

**Comment by zhuzhizhan** [comment]
> > You can use Olimex ARM-USB-Tiny-H connector.
> > Regards,
> > Arup
> 
> Hi,
> 
> I use the ft2232HL as the connector. Can it be used to debug?
> I use it and get some log:
> Open On-Chip Debugger 0.10.0+dev-00849-gcbb15587d (2020-09-10-11:59)
> Licensed under GNU GPL v2
> For bug reports, read
> http://openocd.org/doc/doxygen/bugs.html
> Info : clock speed 100 kHz
> Info : JTAG tap: riscv.cpu tap/device found: 0x00000001 (mfg: 0x000 (), part: 0x0000, ver: 0x0)
> Error: Debug Module did not become active. dmcontrol=0x0
> Info : Listening on port 3333 for gdb connections
> Error: Target not examined yet

I change the swerv_eh1's branch to 1.4 and solve this problem.
