### ISSUE TITLE
Could you please show the utilization of the SoC?

### ISSUE THREAD

**Issue by hyf6661669** [westerndigitalcorporation/swerv_eh1_fpga#4]
Since the low-end FPGA boards from Altera are cheaper than those from Xilinx, many students/beginners like me would choose to buy an Altera board at the beginning. The utilization report from Vivado would help users evaluate the minimal FPGA that could run your SoC successfully.

Much thanks.

**Comment by arupde171** [comment]
Please find the utilization screenshot in below link.
[SWeRV_Nexys4DDR_utilization.pdf](https://github.com/westerndigitalcorporation/swerv_eh1_fpga/files/3184281/SWeRV_Nexys4DDR_utilization.pdf)




Thanks,
Arup

**Comment by hyf6661669** [comment]
@arupde171 
Thanks, really helpful information.
