### ISSUE TITLE
initializing issue while running the swerv core on zed board

### ISSUE THREAD

**Issue by rajat-agnisys** [westerndigitalcorporation/swerv_eh1_fpga#8]
Hello,

I am just trying to run swerv design on xilinx zed board using vivado and instead of running it in the debug mode using jtag and uart, i want to interface this with zedboard io's.
Could you help me in this as i am unable to write firmware sequences for the swerv core in fpga or how to initialize the memory with those hardcode sequence.

Thanks

**Comment by arupde171** [comment]
Hi Rajat,
    You can check the firmware startup file to understand the firmware sequences after loading the program and reset the core.

Thanks,
Arup
